services:
  feeder:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - feeder_db:/data
    environment:
      - DB_PATH=/data/feeder.sqlite
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7389/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - feeder-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7389:80"
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://feeder:7389
    depends_on:
      - feeder
    networks:
      - feeder-network

networks:
  feeder-network:
    driver: bridge

volumes:
  feeder_db:
    driver: local


