line-length = 100
target-version = "py312"

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long (handled by formatter)
    "N806",  # variable in function should be lowercase
]

[lint.per-file-ignores]
"tests/*" = ["E501", "F401"]

