name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install fastapi uvicorn httpx feedparser pydantic-settings python-dotenv sqlmodel aiosqlite apscheduler backoff pyyaml jinja2 python-multipart chardet
    
    - name: Lint with Python
      run: |
        pip install ruff
        ruff check app/
    
    - name: Test syntax
      run: |
        python -m py_compile app/web/server.py app/core/storage.py app/core/config.py app/core/fetcher.py app/core/parser.py app/core/scheduler.py app/core/rate_limit.py app/core/ua.py app/main.py
    
    - name: Build Docker image
      run: |
        docker build -t thefeeder:test .

