name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Cache node modules
      uses: actions/cache@v4
      id: cache-web
      with:
        path: apps/web/node_modules
        key: ${{ runner.os }}-web-${{ hashFiles('apps/web/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-web-
    
    - name: Install dependencies
      run: |
        cd apps/web
        npm ci
    
    - name: Run npm audit
      run: |
        cd apps/web
        npm audit --audit-level=moderate || true
      continue-on-error: true

  docker-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t thefeeder:scan .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: 'thefeeder:scan'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      continue-on-error: true
      with:
        sarif_file: 'trivy-results.sarif'
        wait-for-processing: true

